<?php
$labels = array(
    'name'                  => _x('Memberships', 'Post Type General Name', 'sage'),
    'singular_name'         => _x('Membership', 'Post Type Singular Name', 'sage'),
    'menu_name'             => __('Memberships', 'sage'),
    'name_admin_bar'        => __('Membership', 'sage'),
    'archives'              => __('Membership Archives', 'sage'),
    'attributes'            => __('Membership Attributes', 'sage'),
    'parent_item_colon'     => __('Parent Membership:', 'sage'),
    'all_items'             => __('All Memberships', 'sage'),
    'add_new_item'          => __('Add New Membership', 'sage'),
    'add_new'               => __('Add New', 'sage'),
    'new_item'              => __('New Membership', 'sage'),
    'edit_item'             => __('Edit Membership', 'sage'),
    'update_item'           => __('Update Membership', 'sage'),
    'view_item'             => __('View Membership', 'sage'),
    'view_items'            => __('View Memberships', 'sage'),
    'search_items'          => __('Search Membership', 'sage'),
    'not_found'             => __('Not found', 'sage'),
    'not_found_in_trash'    => __('Not found in Trash', 'sage'),
    'featured_image'        => __('Featured Image', 'sage'),
    'set_featured_image'    => __('Set featured image', 'sage'),
    'remove_featured_image' => __('Remove featured image', 'sage'),
    'use_featured_image'    => __('Use as featured image', 'sage'),
    'insert_into_item'      => __('Insert into Membership', 'sage'),
    'uploaded_to_this_item' => __('Uploaded to this membership', 'sage'),
    'items_list'            => __('Memberships list', 'sage'),
    'items_list_navigation' => __('Memberships list navigation', 'sage'),
    'filter_items_list'     => __('Filter memberships list', 'sage'),
);
$args = array(
    'label'                 => __('Membership', 'sage'),
    'description'           => __('WPWA Membership Plans', 'sage'),
    'labels'                => $labels,
    'supports'              => array('title', 'thumbnail', 'page-attributes'),
    'taxonomies'            => array(''),
    'menu_icon'                         => 'dashicons-screenoptions',
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 4,
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'rewrite'               => array('slug' => 'memberships'),
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'page',
    'show_in_rest'          => true,
    'rest_controller_class' => 'WP_REST_Posts_Controller',
);
register_post_type('cpt_memberships', $args);
