<?php

	$labels = array(
		'name' => __( 'Annual Reports', 'Post Type General Name', 'sage' ),
		'singular_name' => __( 'Annual Report', 'Post Type Singular Name', 'sage' ),
		'menu_name' => __( 'Annual Reports', 'sage' ),
		'name_admin_bar' => __( 'Annual Report', 'sage' ),
		'archives' => __( 'Annual Report Archives', 'sage' ),
		'attributes' => __( 'Annual Report Attributes', 'sage' ),
		'parent_item_colon' => __( 'Parent Annual Report:', 'sage' ),
		'all_items' => __( 'All Annual Reports', 'sage' ),
		'add_new_item' => __( 'Add New Annual Report', 'sage' ),
		'add_new' => __( 'Add New', 'sage' ),
		'new_item' => __( 'New Annual Report', 'sage' ),
		'edit_item' => __( 'Edit Annual Report', 'sage' ),
		'update_item' => __( 'Update Annual Report', 'sage' ),
		'view_item' => __( 'View Annual Report', 'sage' ),
		'view_items' => __( 'View Annual Reports', 'sage' ),
		'search_items' => __( 'Search Annual Report', 'sage' ),
		'not_found' => __( 'Not found', 'sage' ),
		'not_found_in_trash' => __( 'Not found in Trash', 'sage' ),
		'featured_image' => __( 'Featured Image', 'sage' ),
		'set_featured_image' => __( 'Set featured image', 'sage' ),
		'remove_featured_image' => __( 'Remove featured image', 'sage' ),
		'use_featured_image' => __( 'Use as featured image', 'sage' ),
		'insert_into_item' => __( 'Insert into Annual Report', 'sage' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Annual Report', 'sage' ),
		'items_list' => __( 'Annual Reports list', 'sage' ),
		'items_list_navigation' => __( 'Annual Reports list navigation', 'sage' ),
		'filter_items_list' => __( 'Filter Annual Reports list', 'sage' ),
	);
	$args = array(
		'label' => __( 'Annual Report', 'sage' ),
		'description' => __( 'Annual Reports', 'sage' ),
		'labels' => $labels,
		'menu_icon' => 'dashicons-clipboard',
		'supports' => array('title','thumbnail'),
		'taxonomies' => array(),
		'public' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'menu_position' => 5,
		'show_in_admin_bar' => true,
		'show_in_nav_menus' => false,
		'can_export' => true,
		'has_archive' => false,
		'rewrite' => array( 'slug' => 'annual-reports' ),
		'hierarchical' => false,
		'exclude_from_search' => false,
		'show_in_rest' => true,
		'publicly_queryable' => true,
		'capability_type' => 'post',
	);
	register_post_type( 'cpt_annualreports', $args );
