<?php

	$labels = array(
		'name' => __( 'Projects', 'Post Type General Name', 'sage' ),
		'singular_name' => __( 'Project', 'Post Type Singular Name', 'sage' ),
		'menu_name' => __( 'Projects', 'sage' ),
		'name_admin_bar' => __( 'Project', 'sage' ),
		'archives' => __( 'Project Archives', 'sage' ),
		'attributes' => __( 'Project Attributes', 'sage' ),
		'parent_item_colon' => __( 'Parent Project:', 'sage' ),
		'all_items' => __( 'All Projects', 'sage' ),
		'add_new_item' => __( 'Add New Project', 'sage' ),
		'add_new' => __( 'Add New', 'sage' ),
		'new_item' => __( 'New Project', 'sage' ),
		'edit_item' => __( 'Edit Project', 'sage' ),
		'update_item' => __( 'Update Project', 'sage' ),
		'view_item' => __( 'View Project', 'sage' ),
		'view_items' => __( 'View Projects', 'sage' ),
		'search_items' => __( 'Search Project', 'sage' ),
		'not_found' => __( 'Not found', 'sage' ),
		'not_found_in_trash' => __( 'Not found in Trash', 'sage' ),
		'featured_image' => __( 'Featured Image', 'sage' ),
		'set_featured_image' => __( 'Set featured image', 'sage' ),
		'remove_featured_image' => __( 'Remove featured image', 'sage' ),
		'use_featured_image' => __( 'Use as featured image', 'sage' ),
		'insert_into_item' => __( 'Insert into Project', 'sage' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Project', 'sage' ),
		'items_list' => __( 'Projects list', 'sage' ),
		'items_list_navigation' => __( 'Projects list navigation', 'sage' ),
		'filter_items_list' => __( 'Filter Projects list', 'sage' ),
	);
	$args = array(
		'label' => __( 'Project', 'sage' ),
		'description' => __( 'Projects', 'sage' ),
		'labels' => $labels,
		'menu_icon' => 'dashicons-hammer',
		'supports' => array('title', 'editor', 'excerpt', 'thumbnail', ),
		'taxonomies' => array('ct_project-type', ),
		'public' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'menu_position' => 9,
		'show_in_admin_bar' => true,
		'show_in_nav_menus' => true,
		'can_export' => true,
		'has_archive' => 'projects',
		'rewrite' => array( 'slug' => 'projects' ),
		'hierarchical' => true,
		'exclude_from_search' => false,
		'show_in_rest' => true,
		'publicly_queryable' => true,
		'capability_type' => 'post',
	);
	register_post_type( 'cpt_projects', $args );